# fly.toml app configuration file generated for bytehackz2023bot on 2023-11-13T15:55:01+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bytehackz2023bot"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]

[env]
  LOGGING_LEVEL = "10"
  MAX_TICKETS = "5"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
